name: Go

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod download

      - name: Go generate
        run: |
          go generate ./...

      - name: Check if mocks are updated
        uses: setare/git-changes-action@v0.1.3
        with:
          github_token: ${{ github.token }}

      - name: Test
        run: |
          go test github.com/onsi/ginkgo/ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress -coverprofile=coverage.txt

      - name: Upload coverage report
        uses: codecov/codecov-action@2.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
